/*****************************************************************************
 *                                                                           *
 *  Copyright 2018 Rice University                                           *
 *                                                                           *
 *  Licensed under the Apache License, Version 2.0 (the "License");          *
 *  you may not use this file except in compliance with the License.         *
 *  You may obtain a copy of the License at                                  *
 *                                                                           *
 *      http://www.apache.org/licenses/LICENSE-2.0                           *
 *                                                                           *
 *  Unless required by applicable law or agreed to in writing, software      *
 *  distributed under the License is distributed on an "AS IS" BASIS,        *
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. *
 *  See the License for the specific language governing permissions and      *
 *  limitations under the License.                                           *
 *                                                                           *
 *****************************************************************************/
#ifndef PDBCLIENT_H
#define PDBCLIENT_H

#include "PDBCatalogClient.h"
#include "PDBDispatcherClient.h"
#include "ServerFunctionality.h"

#include "Handle.h"
#include "PDBVector.h"
#include "HeapRequest.h"

/**
 * This class provides functionality so users can connect and access
 * different Server functionalities of PDB, such as:
 *
 *  Catalog services
 *  Dispatcher services
 *  Distributed Storage services
 *  Query services
 *
 */

namespace pdb {

    class PDBClient : public ServerFunctionality {

public:

      /**
       * Creates PDBClient
       * @param portIn - the port number of the PDB manager server
       * @param addressIn - the IP address of the PDB manager server
       */
      PDBClient(int portIn, std::string addressIn);

      PDBClient() = default;

      ~PDBClient() = default;

      void registerHandlers(PDBServer &forMe) override {};

      /* Returns the error message generated by a function call.*/
      string getErrorMessage();

      /****
       * Methods for invoking DistributedStorageManager-related operations
       */

      /* Creates a database */
      bool createDatabase(const std::string &databaseName);

      /* Creates a set with a given type (using a template) for an existing
       * database, no page_size needed in arg. */
      template <class DataType>
      bool createSet(const std::string &databaseName, const std::string &setName);

      /* Sends a request to the Catalog Server to shut down the server that we are
       * connected to
       * ... returns true on success */
      bool shutDownServer(std::string &errMsg);

      /****
       * Methods for invoking Catalog-related operations
       */

      /* Sends a request to the Catalog Server to register a user-defined type
       * defined
       * in a shared library. */
      bool registerType(const std::string &fileContainingSharedLib);

      /* Prints the content of the catalog. */
      void
      printCatalogMetadata(pdb::Handle<pdb::CatPrintCatalogRequest> itemToSearch);

      /* Lists all metadata registered in the catalog. */
      void listAllRegisteredMetadata();

      /* Lists the Databases registered in the catalog. */
      void listRegisteredDatabases();

      /* Lists the Sets for a given database registered in the catalog. */
      void listRegisteredSetsForADatabase(const std::string &databaseName);

      /* Lists the Nodes registered in the catalog. */
      void listNodesInCluster();

      /* Lists user-defined types registered in the catalog. */
      void listUserDefinedTypes();

      /**
       *
       * @param setAndDatabase
       * @return
       */
      template <class DataType>
      bool sendData(std::pair<std::string, std::string> setAndDatabase,
                    Handle<Vector<Handle<DataType>>> dataToSend);

      /****
       * Methods for invoking Query-related operations
       */

      /* Deletes a set. */
      bool deleteSet(std::string databaseName, std::string setName);

    private:
      std::shared_ptr<pdb::PDBCatalogClient> catalogClient;
      std::shared_ptr<pdb::PDBDispatcherClient> dispatcherClient;

      std::function<bool(Handle<SimpleRequestResult>)>
      generateResponseHandler(std::string description, std::string &errMsg);

      // Port of the PlinyCompute manager node
      int port;

      // IP address of the PlinyCompute manager node
      std::string address;

      // Error Message (if an error occurred)
      std::string errorMsg;

      // Message returned by a PlinyCompute function
      std::string returnedMsg;

      // Client logger
      PDBLoggerPtr logger;
    };
}

#include "PDBClientTemplate.cc"
#include "PDBDispatcherClientTemplate.cc"

#endif
